define([], function() {
  return {
    "PropertyPageGeneral": "Customize the general settings",
    "PropertyPageTextPanel": "Customize the Text Panel settings",
    "PropertyPageBorder": "Customize the Tiles border settings",
    "PropertyPaneDescription": "Description",
    "BasicGroupName": "Data",
    "DescriptionFieldLabel": "Description Field",
    "GeneralGroupName": "General",
    "BorderGroupName": "Border",
    "TilesTypeFieldLabel": "Justified",
    "EnableIconsFieldLabel": "Enable icons",
    "TextPanelGroupName": "Text Panel",
    "TextPanelEnableFieldLabel": "Enable textpanel",
    "TextPanelAlwaysOnTopFieldLabel": "Always on top",
    "TextPanelPositionFieldLabel": "Position",
    "TextPanelOpacityFieldLabel": "Opacity",
    "TextPanelFontFieldLabel": "Font",
    "TextPanelFontSizeFieldLabel": "Font Size",
    "TextPanelFontColorFieldLabel": "Font Color",
    "TextPanelBackgroundColorFieldLabel": "Background Color",
    "TextPanelAlignFieldLabel": "Text align",
    "EnableShadowFieldLabel": "Enable shadow",
    "EnableBorderFieldLabel": "Enable border",
    "SpaceBetweenColsFieldLabel": "Space between columns",
    "BorderColorFieldLabel": "Border color",
    "BorderFieldLabel": "Border size",
    "ErrorSelectList": "Please edit the webpart and add some news items.",
    "ErrorNoItems": "No items found. Please edit the webpart and add some news items.",
    "Loading": "Loading...",
    "EnableArrows": "Enable Arrows",
    "EnableBullets": "Enable Bullets",
    "EnablePlayButton": "Enable Play Button",
    "EnableFullscreenButton": "Enable Fullscreen Button",
    "EnableZoomPanel": "Enable Zoom Panel",
    "ControlsAlwaysOn": "Controls Always On",
    "PreserveRatio": "Preserve Ratio",
    "PauseOnMouseover": "Pause On Mouseover",
    "Carousel": "Carousel",
    "Autoplay": "Autoplay",
    "Speed": "Speed (ms)",
    "EffectsGroupName": "Effects",
    "Transition": "Transition",
    "EnableProgressIndicator": "Enable Progress Indicator",
    "TileDimension": "Tile Size",
    "ManageItems": "Manage News Items",
    "Items": "News Items"
  }
});