define([], function() {
  return {
    "PropertyPaneDescription": "Personaliza tu WebPart",
    "BasicGroupName": "Ajustes de reproducción",
    "DescriptionFieldLabel": "Descripción",
    "SpeedFieldLabel": "Velocidad",
    "AutoplayFieldLabel": "Función de reproducción automática",
    "AutoplayDelayFieldLabel": "Retardo de reproducción automática",
    "BringtoFrontFieldLabel": "Traer al frente",
    "ShowButtonsFieldLabel": "Mostrar botones",
    "MirrorGapFieldLabel": "Espejo vacío",
    "MirrorHeightFieldLabel": "Altura de espejo",
    "MirrorOpacityFieldLabel": "Opacidad de espejo",
    "YOriginFieldLabel": "Origen Y",
    "YRadiusFieldLabel": "Y radio",
    "XOriginFieldLabel": "Origen X",
    "XRadiusFieldLabel": "X radio",
    "MirrorGroupName": "Espejo",
    "GeneralGroupName": "General",
    "OriginGroupName": "Origen y radio",
    "ShowTitleFieldLabel": "Mostrar título",
    "DataGroupName": "Elementos",
    "DataFieldLabel": "Artículos de carrusel",
    "TitleGroupName": "Título",
    "FontFieldLabel": "Fuente",
    "FontSizeFieldLabel": "Tamaño de fuente",
    "ColorFieldLabel": "Color de fuente",
    "HeightFieldLabel": "Altura",
    "ItemHeightFieldLabel": "Altura del elemento",
    "ReadMore": "Leer más"
  }
});