define([], function() {
  return {
    "PropertyPaneDescription": "Customize your Bar Chart",
    "BasicGroupName": "Data",
    "Width": "Width",
    "Height": "Height",
    "Items": "Items",
    "ManageItems": "Manage Bar Chart Items",
    "Label": "Label",
    "Value": "Value",
    "Color": "Color",
    "HoverColor": "Hover Color",
    "OptionsGroupName": "Bar Settings",
    "Horizontal": "Horizontal",
    "TitleGroupName": "Title Settings",
    "TitleEnable": "Enable",
    "Title": "Title",
    "Position": "Position",
    "TitleFont": "Font",
    "TitleSize": "Font Size",
    "TitleColor": "Color",
    "LegendGroupName": "Legend Settings",
    "LegendEnable": "Enable",
    "LegendPosition": "Position",
    "LegendFont": "Font",
    "LegendSize": "Font Size",
    "LegendColor": "Color",
    "Responsive": "Responsive",
    "XAxesEnable": "x Axe Enable",
    "YAxesEnable": "y Axe Enable",
    "AxesFont": "Axes Font",
    "AxesFontSize": "Axes Font Size",
    "AxesFontColor": "Axes Font Color",
    "BorderWidth": "Border Width"
  }
});