define([], function() {
  return {
    "PropertyPageGeneral": "Customize the general settings",
    "PropertyPageTextPanel": "Customize the Text Panel settings",
    "BasicGroupName": "Data",
    "GeneralGroupName": "General",
    "TextPanelGroupName": "Text Panel",
    "TextPanelEnableFieldLabel": "Enable textpanel",
    "TextPanelAlwaysOnTopFieldLabel": "Always on top",
    "TextPanelOpacityFieldLabel": "Opacity",
    "TextPanelFontFieldLabel": "Font",
    "TextPanelFontSizeFieldLabel": "Font Size",
    "TextPanelBackgroundColorFieldLabel": "Background Color",
    "TextPanelAlignFieldLabel": "Text align",
    "TextPanelFontColorFieldLabel": "Font Color",
    "ErrorSelectList": "Please edit the webpart and add news items.",
    "EffectsGroupName": "Effects",
    "Transition": "Transition",
    "EnableProgressIndicator": "Enable Progress Indicator",
    "EnableArrows": "Enable Arrows",
    "EnableBullets": "Enable Bullets",
    "EnablePlayButton": "Enable Play Button",
    "EnableFullscreenButton": "Enable Fullscreen Button",
    "EnableZoomPanel": "Enable Zoom Panel",
    "ControlsAlwaysOn": "Controls Always On",
    "PreserveRatio": "Preserve Ratio",
    "PauseOnMouseover": "Pause On Mouseover",
    "Carousel": "Carousel",
    "Autoplay": "Autoplay",
    "Speed": "Speed (ms)",
    "Items": "News Items",
    "ManageItems": "Manage News Items"
  }
});