define([], function() {
  return {
    "PropertyPageGeneral": "Personalizar la configuración general",
    "PropertyPageTextPanel": "Personalizar la configuración del Panel de texto",
    "BasicGroupName": "Elementos",
    "GeneralGroupName": "General",
    "TextPanelGroupName": "Panel de texto",
    "TextPanelEnableFieldLabel": "Activar panel de texto",
    "TextPanelAlwaysOnTopFieldLabel": "Siempre en la parte superior",
    "TextPanelOpacityFieldLabel": "Opacidad",
    "TextPanelFontFieldLabel": "Fuente",
    "TextPanelFontSizeFieldLabel": "Tamaño de fuente",
    "TextPanelBackgroundColorFieldLabel": "Color de fondo",
    "TextPanelAlignFieldLabel": "Alinear texto",
    "TextPanelFontColorFieldLabel": "Color de fuente",
    "ErrorSelectList": "Por favor, edita el WebPart y agregar algunas noticias.",
    "EffectsGroupName": "Efectos",
    "Transition": "Transición",
    "EnableProgressIndicator": "Habilitar el indicador de progreso",
    "EnableArrows": "Habilitar flechas",
    "EnableBullets": "Permiten balas",
    "EnablePlayButton": "Activar botón play",
    "EnableFullscreenButton": "Activar pantalla completa botón",
    "EnableZoomPanel": "Activar panel de zoom",
    "ControlsAlwaysOn": "Siempre en los controles",
    "PreserveRatio": "Preservar la relación",
    "PauseOnMouseover": "Pausa en Mouseover",
    "Carousel": "Carrusel",
    "Autoplay": "Función de reproducción automática",
    "Speed": "Velocidad (ms)",
    "Items": "Noticias",
    "ManageItems": "Administrar noticias"
  }
});