define([], function() {
  return {
    "PropertyPageGeneral": "Personnalisez les paramètres généraux",
    "PropertyPageTextPanel": "Personnalisez les panneaux de texte",
    "BasicGroupName": "Données",
    "GeneralGroupName": "Général",
    "TextPanelGroupName": "Panneaux de texte",
    "TextPanelEnableFieldLabel": "Afficher les textes",
    "TextPanelAlwaysOnTopFieldLabel": "Toujours visible",
    "TextPanelOpacityFieldLabel": "Opacité",
    "TextPanelFontFieldLabel": "Police",
    "TextPanelFontSizeFieldLabel": "Taille",
    "TextPanelBackgroundColorFieldLabel": "Couleur de fond",
    "TextPanelAlignFieldLabel": "Alignement du texte",
    "TextPanelFontColorFieldLabel": "Couleur",
    "ErrorSelectList": "Veuillez éditer cette web part et créer de nouveaux éléments.",
    "EffectsGroupName": "Effets",
    "Transition": "Transition",
    "EnableProgressIndicator": "Afficher l'indicateur de progression",
    "EnableArrows": "Afficher les flèches",
    "EnableBullets": "Afficher les points",
    "EnablePlayButton": "Afficher le bouton de lecture",
    "EnableFullscreenButton": "Afficher le bouton de plein écran",
    "EnableZoomPanel": "Afficher le panneau de zoom",
    "ControlsAlwaysOn": "Boutons de contrôle toujours visibles",
    "PreserveRatio": "Preserver le ratio",
    "PauseOnMouseover": "Mettre en pause au passage de la souris",
    "Carousel": "Mode carrousel",
    "Autoplay": "Lecture automatique",
    "Speed": "Vitesse (ms)",
    "Items": "Actualités",
    "ManageItems": "Géter les actualités"
  }
});