define([], function() {
  return {
    "PropertyPaneDescription": "Customize your Polar Chart",
    "BasicGroupName": "Data",
    "Dimension": "Size",
    "Items": "Items",
    "ManageItems": "Manage Polar Items",
    "Label": "Label",
    "Value": "Value",
    "Color": "Color",
    "HoverColor": "Hover Color",
    "OptionsGroupName": "Polar Settings",
    "AnimateRotate": "Animate Rotate",
    "AnimateScale": "Animate Scale",
    "TitleGroupName": "Title Settings",
    "TitleEnable": "Enable",
    "Title": "Title",
    "Position": "Position",
    "TitleFont": "Font",
    "TitleSize": "Font Size",
    "TitleColor": "Color",
    "LegendGroupName": "Legend Settings",
    "LegendEnable": "Enable",
    "LegendPosition": "Position",
    "LegendFont": "Font",
    "LegendSize": "Font Size",
    "LegendColor": "Color",
    "Responsive": "Responsive"
  }
});