define([], function() {
  return {
    "PropertyPaneDescription": "Customize your Text Editor",
    "BasicGroupName": "Text Editor Settings",
    "DescriptionFieldLabel": "Description Field",
    "SpeedFieldLabel": "Speed",
    "AutoplayFieldLabel": "Autoplay",
    "AutoplayDelayFieldLabel": "Autoplay delay",
    "BringtoFrontFieldLabel": "Bring to front",
    "ShowButtonsFieldLabel": "Show buttons",
    "MirrorGapFieldLabel": "Mirror Gap",
    "MirrorHeightFieldLabel": "Mirror height",
    "MirrorOpacityFieldLabel": "Mirror opacity",
    "YOriginFieldLabel": "Y Origin",
    "YRadiusFieldLabel": "Y Radius",
    "XOriginFieldLabel": "X Origin",
    "XRadiusFieldLabel": "X Radius",
    "MirrorGroupName": "Mirror",
    "GeneralGroupName": "General",
    "OriginGroupName": "Origin & Radius",
    "ShowTitleFieldLabel": "Show title",
    "DataGroupName": "Data",
    "DataFieldLabel": "Carousel items",
    "TitleGroupName": "Title",
    "FontFieldLabel": "Font",
    "FontSizeFieldLabel": "Size",
    "ColorFieldLabel": "Color",
    "HeightFieldLabel": "Height",
    "ItemHeightFieldLabel": "Item Height",
    "ItemWidthFieldLabel": "Item Width",
    "ReadMore": "Read more",
    "Easing": "Easing",
    "Density": "Density",
    "InnerOffset": "Inner Offset",
    "InnerScale": "Inner Scale",
    "Shadow": "Enable Shadow",
    "PropertyPageTextPanel": "Customize the Text Panel settings",
    "TextPanelGroupName": "Text Panel",
    "TextPanelEnableFieldLabel": "Enable textpanel",
    "TextPanelAlwaysOnTopFieldLabel": "Always on top",
    "TextPanelPositionFieldLabel": "Position",
    "TextPanelOpacityFieldLabel": "Opacity",
    "TextPanelFontFieldLabel": "Font",
    "TextPanelFontSizeFieldLabel": "Font Size",
    "TextPanelFontColorFieldLabel": "Font Color",
    "TextPanelBackgroundColorFieldLabel": "Background Color",
    "TextPanelAlignFieldLabel": "Text align",
    "Inline": "Inline",
    "Mode": "Toolbar (must refresh page)",
    "Theme": "Theme (must refresh page)",

    "Toolbar": "Show toolbar",
    "ToolbarTips": "Show toolbar tips",
    "Status": "Show status bar",
    "SpellChecker": "Enable spell checker"
  }
});