define([], function() {
  return {
    "PropertyPaneDescription": "Customize your Pie Chart",
    "BasicGroupName": "Data",
    "Width": "Width",
    "Height": "Height",
    "Items": "Items",
    "ManageItems": "Manage Pie Items",
    "Label": "Label",
    "Value": "Value",
    "Color": "Color",
    "HoverColor": "Hover Color",
    "OptionsGroupName": "Pie Settings",
    "CutoutPercentage": "Doughnut Percentage",
    "Rotation": "Rotation",
    "Circumference": "Circumference",
    "AnimateRotate": "Animate Rotate",
    "AnimateScale": "Animate Scale",
    "TitleGroupName": "Title Settings",
    "TitleEnable": "Enable",
    "Title": "Title",
    "Position": "Position",
    "TitleFont": "Font",
    "TitleSize": "Font Size",
    "TitleColor": "Color",
    "LegendGroupName": "Legend Settings",
    "LegendEnable": "Enable",
    "LegendPosition": "Position",
    "LegendFont": "Font",
    "LegendSize": "Font Size",
    "LegendColor": "Color",
    "Responsive": "Responsive"
  }
});