define([], function() {
  return {
    "PropertyPageGeneral": "Customize the general settings",
    "PropertyPageTextPanel": "Customize the Text Panel settings",
    "PropertyPageBorder": "Customize the Tiles border settings",
    "BasicGroupName": "Data",
    "GeneralGroupName": "General",
    "BorderGroupName": "Border",
    "TilesTypeFieldLabel": "Justified",
    "EnableIconsFieldLabel": "Enable icons",
    "TextPanelGroupName": "Text Panel",
    "TextPanelEnableFieldLabel": "Enable textpanel",
    "TextPanelAlwaysOnTopFieldLabel": "Always on top",
    "TextPanelPositionFieldLabel": "Position",
    "TextPanelOpacityFieldLabel": "Opacity",
    "TextPanelFontFieldLabel": "Font",
    "TextPanelFontSizeFieldLabel": "Font Size",
    "TextPanelBackgroundColorFieldLabel": "Background Color",
    "TextPanelAlignFieldLabel": "Text align",
    "TextPanelFontColorFieldLabel": "Font Color",
    "EnableShadowFieldLabel": "Enable shadow",
    "EnableBorderFieldLabel": "Enable border",
    "SpaceBetweenColsFieldLabel": "Space between columns",
    "BorderColorFieldLabel": "Border color",
    "BorderFieldLabel": "Border size",
    "ErrorSelectList": "Please edit the webpart and add menu items to create the tiles menu.",
    "ManageItems": "Manage Menu Items",
    "Items": "Menu Items"
  }
});