define([], function() {
  return {
    "PropertyPageGeneral": "Personalizar la configuración general",
    "PropertyPageTextPanel": "Personalizar la configuración del Panel de texto",
    "PropertyPageBorder": "Personalizar la configuración de los bordes",
    "BasicGroupName": "Elementos",
    "GeneralGroupName": "General",
    "BorderGroupName": "Bordes",
    "TilesTypeFieldLabel": "Justificado",
    "EnableIconsFieldLabel": "Activar los iconos",
    "TextPanelGroupName": "Panel de texto",
    "TextPanelEnableFieldLabel": "Activar panel de texto",
    "TextPanelAlwaysOnTopFieldLabel": "Siempre en la parte superior",
    "TextPanelPositionFieldLabel": "Posición",
    "TextPanelOpacityFieldLabel": "Opacidad",
    "TextPanelFontFieldLabel": "Fuente",
    "TextPanelFontSizeFieldLabel": "Tamaño de fuente",
    "TextPanelBackgroundColorFieldLabel": "Color de fondo",
    "TextPanelAlignFieldLabel": "Alinear texto",
    "TextPanelFontColorFieldLabel": "Color de fuente",
    "EnableShadowFieldLabel": "Habilitar sombra",
    "EnableBorderFieldLabel": "Habilitar la borde",
    "SpaceBetweenColsFieldLabel": "Espacio entre columnas",
    "BorderColorFieldLabel": "Color del borde",
    "BorderFieldLabel": "Tamaño de borde",
    "ErrorSelectList": "Por favor, edita el WebPart y agregar elementos de menú para crear el menú de azulejos.",
    "ManageItems": "Administrar artículos de menú",
    "Items": "Elementos de menú"
  }
});