define([], function() {
  return {
    "PropertyPageTextPanel": "Personalizar la configuración del Panel de texto",
    "PropertyPageGeneral": "Personalizar la configuración general",
    "BasicGroupName": "Datos",
    "GeneralGroupName": "General",
    "EnableArrows": "Habilitar flechas",
    "EnableBullets": "Permiten balas",
    "EnablePlayButton": "Activar botón play",
    "EnableFullscreenButton": "Activar botón de pantalla completa",
    "EnableZoomPanel": "Activar Panel de Zoom",
    "ControlsAlwaysOn": "Siempre en los controles",
    "TextPanelGroupName": "Panel de texto",
    "TextPanelEnableFieldLabel": "Permiten textpanel",
    "TextPanelAlwaysOnTopFieldLabel": "Siempre en la parte superior",
    "TextPanelOpacityFieldLabel": "Opacidad",
    "TextPanelFontFieldLabel": "Fuente",
    "TextPanelFontSizeFieldLabel": "Tamaño de fuente",
    "TextPanelBackgroundColorFieldLabel": "Color de fondo",
    "TextPanelAlignFieldLabel": "Alinear texto",
    "TextPanelFontColorFieldLabel": "Color de fuente",
    "ErrorSelectList": "Por favor, edita el elemento Web y seleccione una biblioteca de imágenes. Si la lista de desplegable cuadro biblioteca está vacía, por favor crea una nueva biblioteca de imágenes en el sitio web actual.",
    "EffectsGroupName": "Efectos",
    "Transition": "Transición",
    "EnableProgressIndicator": "Habilitar el indicador de progreso",
    "PreserveRatio": "Preservar la relación",
    "PauseOnMouseover": "Pausa en Mouseover",
    "Carousel": "Carrusel",
    "Autoplay": "Función de reproducción automática",
    "Speed": "Velocidad (ms)"
  }
});