define([], function() {
  return {
    "PropertyPageTextPanel": "Personnalisez les zones de texte",
    "PropertyPageGeneral": "Personnalisez les paramètres généraux",
    "BasicGroupName": "Données",
    "GeneralGroupName": "Général",
    "EnableArrows": "Afficher les flèches",
    "EnableBullets": "Afficher les bulles",
    "EnablePlayButton": "Afficher le bouton de lecture",
    "EnableFullscreenButton": "Afficher le bouton de plein écran",
    "EnableZoomPanel": "Afficher le panneau de zoom",
    "ControlsAlwaysOn": "Contrôles toujours visibles",
    "TextPanelGroupName": "Zone de texte",
    "TextPanelEnableFieldLabel": "Afficher les textes",
    "TextPanelAlwaysOnTopFieldLabel": "Toujours visible",
    "TextPanelOpacityFieldLabel": "Opacité",
    "TextPanelFontFieldLabel": "Police",
    "TextPanelFontSizeFieldLabel": "Taille",
    "TextPanelBackgroundColorFieldLabel": "Couleur de fond",
    "TextPanelAlignFieldLabel": "Alignement du texte",
    "TextPanelFontColorFieldLabel": "Couleur du texte",
    "ErrorSelectList": "Veuillez éditer cette web part et sélectionner une bibliothèque d'images. Si la liste est vide, veuillez créer une nouvelle bibliothèque dans le site actuel.",
    "EffectsGroupName": "Effets",
    "Transition": "Transition",
    "EnableProgressIndicator": "Afficher l'indicateur de progression",
    "PreserveRatio": "Preserver les ratios",
    "PauseOnMouseover": "Mettre en pause au survol de la souris",
    "Carousel": "Mode carrousel",
    "Autoplay": "Lecture automatique",
    "Speed": "Vitesse (ms)"
  }
});