define([], function() {
  return {
    "PropertyPageGeneral": "Customize the general settings",
    "PropertyPageTextPanel": "Customize the Text Panel settings",
    "PropertyPageBorder": "Customize the Tiles border settings",
    "PropertyPaneDescription": "Description",
    "BasicGroupName": "Data",
    "DescriptionFieldLabel": "Description Field",
    "GeneralGroupName": "General",
    "BorderGroupName": "Border",
    "TilesTypeFieldLabel": "Justified",
    "EnableIconsFieldLabel": "Enable icons",
    "TextPanelGroupName": "Text Panel",
    "TextPanelEnableFieldLabel": "Enable textpanel",
    "TextPanelAlwaysOnTopFieldLabel": "Always on top",
    "TextPanelPositionFieldLabel": "Position",
    "TextPanelOpacityFieldLabel": "Opacity",
    "TextPanelFontFieldLabel": "Font",
    "TextPanelFontSizeFieldLabel": "Font Size",
    "TextPanelFontColorFieldLabel": "Font Color",
    "TextPanelBackgroundColorFieldLabel": "Background Color",
    "TextPanelAlignFieldLabel": "Text align",
    "EnableShadowFieldLabel": "Enable shadow",
    "EnableBorderFieldLabel": "Enable border",
    "SpaceBetweenColsFieldLabel": "Space between columns",
    "BorderColorFieldLabel": "Border color",
    "BorderFieldLabel": "Border size",
    "ErrorSelectList": "Please edit the webpart and select a picture library. If the picture library dropdown list is empty, please create a new Picture Library in the current web site.",
    "ErrorNoItems": "No items found in the current library. Please insert inside or select another library.",
    "Loading": "Loading pictures...",
    "EnableArrows": "Enable Arrows",
    "EnableBullets": "Enable Bullets",
    "EnablePlayButton": "Enable Play Button",
    "EnableFullscreenButton": "Enable Fullscreen Button",
    "EnableZoomPanel": "Enable Zoom Panel",
    "ControlsAlwaysOn": "Controls Always On",
    "PreserveRatio": "Preserve Ratio",
    "PauseOnMouseover": "Pause On Mouseover",
    "Carousel": "Carousel",
    "Autoplay": "Autoplay",
    "Speed": "Speed (ms)",
    "EffectsGroupName": "Effects",
    "Transition": "Transition",
    "EnableProgressIndicator": "Enable Progress Indicator",
    "TileDimension": "Tiles Size",
    "Position": "Grid Panel Position",
    "NumCols": "Number of columns"
  }
});