define([], function() {
  return {
    "PropertyPageGeneral": "Personalizar la configuración general",
    "PropertyPageTextPanel": "Personalizar la configuración del Panel de texto",
    "PropertyPageBorder": "Personalizar la configuración de los bordes",
    "PropertyPaneDescription": "Descripción",
    "BasicGroupName": "Elementos",
    "DescriptionFieldLabel": "Descripción",
    "GeneralGroupName": "General",
    "BorderGroupName": "Bordes",
    "TilesTypeFieldLabel": "Justificado",
    "EnableIconsFieldLabel": "Activar los iconos",
    "TextPanelGroupName": "Panel de texto",
    "TextPanelEnableFieldLabel": "Activar panel de texto",
    "TextPanelAlwaysOnTopFieldLabel": "Siempre en la parte superior",
    "TextPanelPositionFieldLabel": "Posición",
    "TextPanelOpacityFieldLabel": "Opacidad",
    "TextPanelFontFieldLabel": "Fuente",
    "TextPanelFontSizeFieldLabel": "Tamaño de fuente",
    "TextPanelFontColorFieldLabel": "Color de fuente",
    "TextPanelBackgroundColorFieldLabel": "Color de fondo",
    "TextPanelAlignFieldLabel": "Alinear texto",
    "EnableShadowFieldLabel": "Habilitar sombra",
    "EnableBorderFieldLabel": "Habilitar la borde",
    "SpaceBetweenColsFieldLabel": "Espacio entre columnas",
    "BorderColorFieldLabel": "Color del borde",
    "BorderFieldLabel": "Tamaño de borde",
    "ErrorSelectList": "Por favor, edita el WebPart y seleccione una biblioteca de imágenes. Si la lista de desplegable cuadro biblioteca está vacía, por favor crea una nueva biblioteca de imágenes en el sitio web actual.",
    "ErrorNoItems": "No se encuentren en la biblioteca actual. Por favor inserte dentro o selecciona otra biblioteca.",
    "Loading": "Cuadros de carga...",
    "EnableArrows": "Habilitar flechas",
    "EnableBullets": "Permiten balas",
    "EnablePlayButton": "Activar botón play",
    "EnableFullscreenButton": "Activar pantalla completa botón",
    "EnableZoomPanel": "Activar panel de zoom",
    "ControlsAlwaysOn": "Siempre en los controles",
    "PreserveRatio": "Preservar la relación",
    "PauseOnMouseover": "Pausa en Mouseover",
    "Carousel": "Carrusel",
    "Autoplay": "Función de reproducción automática",
    "Speed": "Velocidad (ms)",
    "EffectsGroupName": "Efectos",
    "Transition": "Transición",
    "EnableProgressIndicator": "Habilitar el indicador de progreso",
    "TileDimension": "Tamaño de azulejos",
    "Position": "Posición de la rejilla",
    "NumCols": "Número de columnas"
  }
});