define([], function() {
  return {
    "PropertyPageGeneral": "Personnalisez les paramètres généraux",
    "PropertyPageTextPanel": "Personnalisez les paramètres des textes",
    "PropertyPageBorder": "Personnalisez les vignettes",
    "PropertyPaneDescription": "Description",
    "BasicGroupName": "Données",
    "DescriptionFieldLabel": "Description",
    "GeneralGroupName": "Général",
    "BorderGroupName": "Bordures",
    "TilesTypeFieldLabel": "Justifié",
    "EnableIconsFieldLabel": "Affiche les icônes",
    "TextPanelGroupName": "Panneaux textuels",
    "TextPanelEnableFieldLabel": "Afficher les textes",
    "TextPanelAlwaysOnTopFieldLabel": "Toujours visible",
    "TextPanelPositionFieldLabel": "Position",
    "TextPanelOpacityFieldLabel": "Opacité",
    "TextPanelFontFieldLabel": "Police",
    "TextPanelFontSizeFieldLabel": "Taille",
    "TextPanelFontColorFieldLabel": "Couleur",
    "TextPanelBackgroundColorFieldLabel": "Couleur de texte",
    "TextPanelAlignFieldLabel": "Alignement du texte",
    "EnableShadowFieldLabel": "Afficher les ombres",
    "EnableBorderFieldLabel": "Afficher les bords",
    "SpaceBetweenColsFieldLabel": "Espace entre les colonnes",
    "BorderColorFieldLabel": "Couleur des bords",
    "BorderFieldLabel": "Taille des bords",
    "ErrorSelectList": "Veuillez éditer cette web part et sélectionner une bibliothèque d'images. Si la liste est vide, veuillez créer une nouvelle bibliothèque de document dans le site actuel.",
    "ErrorNoItems": "Aucune image trouvée. Veuillez en insérer ou sélectionner une autre bibliothèque d'images.",
    "Loading": "Chargement des images...",
    "EnableArrows": "Afficher les flèches",
    "EnableBullets": "Afficher les indicateurs ronds",
    "EnablePlayButton": "Afficher le bouton de lecture",
    "EnableFullscreenButton": "Afficher le bouton de plein écran",
    "EnableZoomPanel": "Afficher le panneau de zoom",
    "ControlsAlwaysOn": "Boutons toujours visibles",
    "PreserveRatio": "Preservé le ratio",
    "PauseOnMouseover": "Pause au passage de la souris",
    "Carousel": "Carrousel",
    "Autoplay": "Lecture automatique",
    "Speed": "Vitesse (ms)",
    "EffectsGroupName": "Effets",
    "Transition": "Transition",
    "EnableProgressIndicator": "Afficher l'indicateur d'avancement",
    "TileDimension": "Taille des vignettes",
    "Position": "Position du panneau de vignettes",
    "NumCols": "Nombre de colonnes"
  }
});