define([], function() {
  return {
    "PropertyPageGeneral": "Customize the general settings",
    "PropertyPageTextPanel": "Customize the Text Panel settings",
    "PropertyPageBorder": "Customize the Tiles border settings",
    "BasicGroupName": "Data",
    "GeneralGroupName": "General",
    "BorderGroupName": "Border",
    "EnableIconsFieldLabel": "Enable icons",
    "TextPanelGroupName": "Text Panel",
    "TextPanelEnableFieldLabel": "Enable textpanel",
    "TextPanelAlwaysOnTopFieldLabel": "Always on top",
    "TextPanelOpacityFieldLabel": "Opacity",
    "TextPanelFontFieldLabel": "Font",
    "TextPanelFontSizeFieldLabel": "Font Size",
    "TextPanelBackgroundColorFieldLabel": "Background Color",
    "TextPanelAlignFieldLabel": "Text align",
    "TextPanelFontColorFieldLabel": "Font Color",
    "EnableBorderFieldLabel": "Enable border",
    "BorderColorFieldLabel": "Border color",
    "BorderFieldLabel": "Border size",
    "ErrorSelectList": "Please edit the webpart and select a picture library. If the picture library dropdown list is empty, please create a new Picture Library in the current web site.",
    "EffectsGroupName": "Effects",
    "EnableArrows": "Enable Arrows",
    "PauseOnMouseover": "Pause On Mouseover",
    "Autoplay": "Autoplay",
    "Speed": "Speed (ms)",
    "Dimension": "Tile Size"
  }
});