define([], function() {
  return {
    "PropertyPageGeneral": "Personalizar la configuración general",
    "PropertyPageTextPanel": "Personalizar la configuración del Panel de texto",
    "PropertyPageBorder": "Personalizar la configuración de los bordes",
    "BasicGroupName": "Elementos",
    "GeneralGroupName": "General",
    "BorderGroupName": "Bordes",
    "EnableIconsFieldLabel": "Activar los iconos",
    "TextPanelGroupName": "Panel de texto",
    "TextPanelEnableFieldLabel": "Permiten textpanel",
    "TextPanelAlwaysOnTopFieldLabel": "Siempre en la parte superior",
    "TextPanelOpacityFieldLabel": "Opacidad",
    "TextPanelFontFieldLabel": "Fuente",
    "TextPanelFontSizeFieldLabel": "Tamaño de fuente",
    "TextPanelBackgroundColorFieldLabel": "Color de fondo",
    "TextPanelAlignFieldLabel": "Alinear texto",
    "TextPanelFontColorFieldLabel": "Color de fuente",
    "EnableBorderFieldLabel": "Habilitar la borde",
    "BorderColorFieldLabel": "Color del borde",
    "BorderFieldLabel": "Tamaño de borde",
    "ErrorSelectList": "Por favor, edita el elemento Web y seleccione una biblioteca de imágenes. Si la lista de desplegable cuadro biblioteca está vacía, por favor crea una nueva biblioteca de imágenes en el sitio web actual.",
    "EffectsGroupName": "Efectos",
    "EnableArrows": "Habilitar flechas",
    "PauseOnMouseover": "Pausa en Mouseover",
    "Autoplay": "Función de reproducción automática",
    "Speed": "Velocidad (ms)",
    "Dimension": "Tamaño del azulejo"
  }
});