define([], function() {
  return {
    "PropertyPageGeneral": "Personnalisez les paramètres généraux",
    "PropertyPageTextPanel": "Personnalisez les zones de texte",
    "PropertyPageBorder": "Personnalisez les vignettes",
    "BasicGroupName": "Données",
    "GeneralGroupName": "Général",
    "BorderGroupName": "Bords",
    "EnableIconsFieldLabel": "Afficher les icônes",
    "TextPanelGroupName": "Zone de texte",
    "TextPanelEnableFieldLabel": "Afficher les textes",
    "TextPanelAlwaysOnTopFieldLabel": "Toujours visible",
    "TextPanelOpacityFieldLabel": "Opacité",
    "TextPanelFontFieldLabel": "Police",
    "TextPanelFontSizeFieldLabel": "Taille",
    "TextPanelBackgroundColorFieldLabel": "Couleur de fond",
    "TextPanelAlignFieldLabel": "Alignement du texte",
    "TextPanelFontColorFieldLabel": "Couleur",
    "EnableBorderFieldLabel": "Afficher les bords",
    "BorderColorFieldLabel": "Couleur des bords",
    "BorderFieldLabel": "Tailles des bords",
    "ErrorSelectList": "Veuillez éditer cette web part et sélectionner une bibliothèque d'images. Si la liste est vide, veuillez créer une nouvelle bibliothèque d'images dans le site actuel.",
    "EffectsGroupName": "Effets",
    "EnableArrows": "Afficher les flèches",
    "PauseOnMouseover": "Mettre en pause au survol de la souris",
    "Autoplay": "Lecture automatique",
    "Speed": "Vitesse (ms)",
    "Dimension": "Taille des vignettes"
  }
});